### ISSUE TITLE
Move to NSSpeechSynthesizer

### ISSUE THREAD

**Issue by youknowone** [youknowone/Say#1]
Reference: https://developer.apple.com/reference/appkit/nsspeechsynthesizer

The impelentaiton depends on `say` the command-line voice synthesizer in mac.
There is NSSpeechSynthesizer with better API interface.

**Comment by youknowone** [comment]
Backward compatibility - mostly for fun.
NSSpeechSynthesizer is available 10.10+. We can create alternative implementation of NSSpeechSynthesizer using `say`

**Comment by closer27** [comment]
Hi, I think I can handle it. It's my first time to develop macOS app, but It looks like funny.

**Comment by closer27** [comment]
#36 I've done it. review plz 😆

**Comment by closer27** [comment]
I think we'd better to change this issue to close 🙋🏻‍♂️

**Comment by youknowone** [comment]
Thanks!
