### ISSUE TITLE
Reading web page

### ISSUE THREAD

**Issue by kjy95** [youknowone/Say#15]
Blind can't read web page. So they can't get brand-new information easily. Some page have reading function but most page don't support it.
I think if this app support "reading web page function", blind will be convenient.

**Comment by pmw9027** [comment]
I think It is a good idea
How about using twitter API service?
Is twitter based on text?

**Comment by youknowone** [comment]
Twitter itself has heavy UI, but they are suggesting API to retrieve text.

https://dev.twitter.com/rest/public

**Comment by kjy95** [comment]
I finished it
