### ISSUE TITLE
Feature request: set speaking rate

### ISSUE THREAD

**Issue by closer27** [youknowone/Say#30]
I saw the suggestion that It must be good to have `play/stop` feature below.
In addition to that, I think `Rate` feature is very useful for studying English.
I mean that `Say` will be able to **control speeching speed** by using a component like slider.

How about this idea?

**Comment by youknowone** [comment]
#3 was intending this issue. I think this is an important feature.

**Comment by closer27** [comment]
Oh, I missed It's already exist.
