### ISSUE TITLE
I found Bug on Saying

### ISSUE THREAD

**Issue by pmw9027** [youknowone/Say#31]
On Saying text, Can't Control with spinning pinwheel

**Comment by youknowone** [comment]
I don't understand it - what is the spinning and the pinwheel. Would you attach a screenshot for the detail?

**Comment by pmw9027** [comment]
After Clicking say button , The app is going to be freezing.
In Capture, not showing the mouse...

**Comment by youknowone** [comment]
I got it. it is #2 and @sikeeo is fixing it.

**Comment by closer27** [comment]
umm. When I see, only `Say` for `iOS` has been fixed. `macOS` version is still being.

**Comment by closer27** [comment]
I've found that it's been fixed at the recent version. Sorry!!
